src/Sms.WebAdmin/Controllers/ConsoleController.cs
using Sms.Common;
using Sms.Entity.ViewModel;
using Sms.WebAdmin.Common;
using Sms.WebAdmin.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Sms.WebAdmin.Controllers
{
    public class ConsoleController : BaseController
    {
        /// <summary>
        /// 控制台全局框架
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //根据登录用户的权限获取菜单节点，放到缓存中，下次直接从缓存读取
            List<MenuNode> menu = new List<MenuNode>();
            var cache = CacheHelper.GetCache(ConstFiled.GlobalMenu + CurrentLoginUser.Id);
            if (cache != null)
            {
                menu = cache as List<MenuNode>;
            }
            else
            {
                //1.从数据库查询
                //模块列表
                var moduleList = _repositoryFactory.ISystemModule.Where(m => m.IsDisplay && m.ParentId != 0, m => m.Sort, true).ToList();
                if (!CurrentLoginUser.IsSuperUser)
                {
                    if (!string.IsNullOrEmpty(CurrentLoginUser.RoleString))
                    {
                        IEnumerable<int> role = CurrentLoginUser.RoleString.Split(',').Select(m => Convert.ToInt32(m));
                        //找到拥有查看权限的模块id
                        var roleRight = _repositoryFactory.ISystemRoleRight.Where(m => role.Contains(m.RoleId) && m.RightId == (int)EnumHepler.ActionPermission.View).Select(m => m.ModuleId).Distinct();
                        //从所有模块中移除没有查看权限的
                        moduleList.RemoveAll(m => !roleRight.Contains(m.Id));
                    }
                    else
                    {
                        //一个角色都么有肯定也就没有任何菜单了
                        moduleList.Clear();
                    }
                }
                var top = _repositoryFactory.ISystemModule.Where(m => m.IsDisplay && m.ParentId == 0, m => m.Sort, true).Select(m => new { m.Id, m.Name, m.Url }).ToList();
                foreach (var module in top)
                {
                    var child = moduleList.Where(m => m.ParentId == module.Id).OrderBy(m => m.Sort);
                    if (child.Count() > 0)
                    {
                        MenuNode node = new MenuNode();
                        node.Title = module.Name;
                        node.Id = module.Id;
                        foreach (var c in child)
                        {
                            node.ChildNode.Add(new MenuNode() { Id = c.Id, Title = c.Name, Url = c.Url });
                        }
                        menu.Add(node);
                    }
                }
                //2.放入缓存
                CacheHelper.SetCache(ConstFiled.GlobalMenu + CurrentLoginUser.Id, menu, TimeSpan.FromMinutes(10));
            }
            ViewBag.CurrentUser = CurrentLoginUser;
            return View(menu);
        }

        /// <summary>
        /// 控制台首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Home()
        {
            return View();
        }

        /// <summary>
        /// 获取当前登录用户的信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetLoginUserDetail()
        {
            var current = CurrentLoginUser;
            if (current.IsSuperUser)
            {
                string path = HttpContext.Server.MapPath("/App_Data/adminconfig.xml");
                XmlDocument config = new XmlDocument();
                config.Load(path);
                return Json(new TipMessage()
                {
                    Status = true,
                    MsgText = "获取信息成功",
                    Data = new
                    {
                        UserName = config.SelectSingleNode("root/SuperUser").InnerText,
                        TrueName = "超级管理员",
                        LinkPhone = "",
                        LastLoginTime = config.SelectSingleNode("root/LastLoginTime").InnerText,
                        CreateTime = "系统自动创建",
                        RoleList = "所有"
                    }
                }, JsonRequestBehavior.DenyGet);
            }
            var user = _repositoryFactory.ISystemUser.Single(m => m.Id == current.Id);
            if (user != null)
            {
                StringBuilder roleString = new StringBuilder();
                int[] roleArry = user.RoleList.Split(',').Select(m => int.Parse(m)).ToArray();
                var roles = _repositoryFactory.ISystemRole.Where(m => roleArry.Contains(m.Id)).Select(m => m.Name).ToList();
                foreach (var item in roles)
                {
                    roleString.Append(item + "、");
                }
                return Json(new TipMessage()
                {
                    Status = true,
                    MsgText = "获取信息成功",
                    Data = new
                    {
                        user.UserName,
                        user.TrueName,
                        user.LinkPhone,
                        LastLoginTime = user.LastLoginTime != null ? user.LastLoginTime.Value.ToString("yyyy-MM-dd HH:mm:ss") : "",
                        CreateTime = user.CreateTime != null ? user.CreateTime.Value.ToString("yyyy-MM-dd HH:mm:ss") : "",
                        RoleList = roleString.Length > 0 ? roleString.ToString().TrimEnd('、') : ""
                    }
                }, JsonRequestBehavior.DenyGet);
            }
            return Json(new TipMessage() { Status = false, MsgText = "获取信息失败" }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 清除缓存和session
        /// </summary>
        /// <returns></returns>
        public ActionResult ClearCache()
        {
            var cache = HttpContext.Cache.GetEnumerator();
            while (cache.MoveNext())
            {
                HttpContext.Cache.Remove(cache.Key.ToString());
            }
            Session.Clear();
            return Json(new TipMessage() { Status = true, MsgText = "清除成功！" }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 当前用户修改密码
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> ChangePassword(ChangePassword model)
        {
            if (ModelState.IsValid)
            {
                if (!model.ConfirmNewPwd.Equals(model.NewPwd))
                {
                    return ShowResultMessage(new TipMessage() { Status = false, MsgText = "确认新密码错误！" });
                }
                var current = CurrentLoginUser;
                if (current.IsSuperUser)
                {
                    string path = HttpContext.Server.MapPath("/App_Data/adminconfig.xml");
                    XmlDocument config = new XmlDocument();
                    config.Load(path);
                    var old = config.SelectSingleNode("root/SuperUserPassword").InnerText;
                    if (old.Equals(SecurityHelper.MD5(model.OldPwd)))
                    {

                        config.SelectSingleNode("root/SuperUserPassword").InnerText = SecurityHelper.MD5(model.NewPwd);
                        config.Save(path);
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "修改成功！", Url = Url.Action("LoginOut", "Login") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "旧密码输入错误！" });
                    }
                }
                else
                {
                    var user = await _repositoryFactory.ISystemUser.SingleAsync(m => m.Id == CurrentLoginUser.Id);
                    if (!user.Password.Equals(SecurityHelper.MD5(model.OldPwd)))
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "旧密码输入错误！" });
                    }
                    user.Password = SecurityHelper.MD5(model.NewPwd);
                    _repositoryFactory.ISystemUser.Modify(user, "Password");
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "修改成功！", Url = Url.Action("LoginOut", "Login") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "修改失败！" });
                    }
                }
            }
            return View();
        }
    }
}

src/Sms.WebAdmin/Controllers/PromotionController.cs
using Sms.Common;
using Sms.Entity;
using Sms.Entity.ViewModel;
using Sms.WebAdmin.Common;
using Sms.WebAdmin.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace Sms.WebAdmin.Controllers
{
    public class PromotionController : BaseController
    {
        /// <summary>
        /// 促销活动列表页
        /// </summary>
        /// <param name="keyword"></param>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Index(string keyword = "")
        {
            var list = _repositoryFactory.IPromotion.Where(c => c.Status != (int)EnumHepler.PromotionStatus.Deleted);
            //搜索关键字过滤
            if (!string.IsNullOrEmpty(keyword))
            {
                list = list.Where(c => c.Title.Contains(keyword));
            }
            list = list.OrderByDescending(c => c.CreateTime);
            var pagerList = list.ToPagedList(PageIndex, ConstFiled.PageSize);
            return View(pagerList);
        }

        /// <summary>
        /// 促销活动信息编辑页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Edit(int? id )
        {
            if (id == 0)
            {
                return View();
            }
            var model = _repositoryFactory.IPromotion.Single(m => m.Id == id);
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// 促销活动信息编辑处理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(true, EnumHepler.ActionPermission.New)]
        public async Task<ActionResult> Edit(Promotion model)
        {
            if (ModelState.IsValid)
            {
                if (model.StartDate >= model.EndDate)
                {
                    return ShowResultMessage(new TipMessage() { Status = false, MsgText = "开始日期必须小于结束日期！"});
                }
                if (model.Id>0)
                {
                    _repositoryFactory.IPromotion.Modify(model, "Title", "Type", "StartDate", "EndDate", "MinValue", "Money", "Status");
                    WriteLog($"修改了促销活动【{model.Title}】的信息");
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "编辑成功！", Url = Url.Action("Index") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "编辑失败！", Url = Url.Action("Edit", new { id = model.Id }) });
                    }
                }
                else
                {
                    model.CreateTime = DateTime.Now;
                    model.CreateUser = CurrentLoginUser.UserName;
                    _repositoryFactory.IPromotion.Add(model);
                    WriteLog($"创建了促销活动【{model.Title}】");
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "添加成功！", Url = Url.Action("Index") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "添加失败！"});
                    }
                }
            }
            return ShowResultMessage(new TipMessage() { Status = false, MsgText = "未知操作结果！" });
        }

        /// <summary>
        /// 修改状态
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">更新的状态编号</param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.ChangeStatus)]
        public async Task<ActionResult> UpdateStatus(int id, int status)
        {
            var entity = _repositoryFactory.IPromotion.Single(m => m.Id == id);
            if (entity != null)
            {
                entity.Status = status;
                _repositoryFactory.IPromotion.Modify(entity, "Status");
                WriteLog($"变更了促销活动【{entity.Title}】的状态");
                if (await _repositoryFactory.SaveChanges() > 0)
                {
                    return Json(new TipMessage() { Status = true, MsgText = "操作成功", Url = Url.Action("Index") }, JsonRequestBehavior.DenyGet);
                }
            }
            return Json(new TipMessage() { Status = false, MsgText = "操作失败" }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.Delete)]
        public async Task<ActionResult> PromotionDelete(int id)
        {
            var entity = _repositoryFactory.IPromotion.Single(m => m.Id == id);
            if (entity != null)
            {
                 entity.Status = (int)EnumHepler.PromotionStatus.Deleted;
                _repositoryFactory.IPromotion.Modify(entity, "Status");
                WriteLog($"删除了促销活动【{entity.Title}】");
                if (await _repositoryFactory.SaveChanges() > 0)
                {
                    return Json(new TipMessage() { Status = true, MsgText = "删除成功"}, JsonRequestBehavior.DenyGet);
                }
            }
            return Json(new TipMessage() { Status = false, MsgText = "删除失败" }, JsonRequestBehavior.DenyGet);
        }
    }
}

src/Sms.WebAdmin/Views/Promotion/Edit.cshtml
@model Sms.Entity.Promotion
@using Sms.Common
@section head{

    <link href="~/Content/datepicker.css" rel="stylesheet" />
}
<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">销售管理</a>
    <a href="@Url.Action("Index", "Promotion")" title="促销列表" class="tip-bottom">门店促销</a>
    <a href="javascript:void(0);" class="current">编辑促销信息</a>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                @using (Ajax.BeginForm("Edit", "Promotion", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "OnSubmiting", OnComplete = "AjaxCompelement" }, new { @class = "form-horizontal", id = "EditPromotion" }))
                {
                    if (Model != null)
                    { @Html.HiddenFor(m => m.Id);
                    }

                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-pencil"></i>
                        </span>
                        <h5>编辑促销信息</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <div class="control-group">
                            <label class="control-label">标题</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Title, new { @style = "width:300px" })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">类型</label>
                            <div class="controls">
                                @{
                                    Dictionary<string, int> dictType = EnumHepler.GetEnumData(typeof(EnumHepler.PromotionType));
                                }
                                @Html.DropDownListFor(model => model.Type, new SelectList(dictType, "Value", "Key", true), "", new { @style = "width:100px" })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">开始日期</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.StartDate)
                                00:00:00
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">结束日期</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.EndDate)
                                23:59:59
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">最低金额</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.MinValue)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">满减/赠送 金额</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Money)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">状态</label>
                            <div class="controls">
                                @{
                                    Dictionary<string, int> dictStatus = EnumHepler.GetEnumData(typeof(EnumHepler.PromotionStatus));
                                    dictStatus.Remove(EnumHepler.GetEnumDescription(EnumHepler.PromotionStatus.Deleted));
                                }
                                @Html.DropDownListFor(model => model.Status, new SelectList(dictStatus, "Value", "Key", true), "", new { @style = "width:100px" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="submit" value="保存" class="btn btn-primary" />
                            <input type="button" value="返回" class="btn" onclick="location.href='@Url.Action("Index")    '" />
                        </div>
                    </div>
                    <div class="widget-content">
                        <ul class="activity-list">
                            <li>
                                <a href="javascript:void(0);">
                                    <i class="icon-info-sign"></i>
                                    满足多种促销条件时默认使用<strong>最新发布的</strong>
                                </a>
                            </li>
                        </ul>
                    </div>
                                    }
            </div>
        </div>
    </div>
</div>
@section foot{
    <script src="~/Scripts/unicorn/jquery.ui.custom.js"></script>
    <script src="~/Scripts/unicorn/bootstrap-datepicker.js"></script>
    <script>
        $(function () {
            $("#StartDate,#EndDate").datepicker();
            var rules = {
                Title: {
                    required: true,
                    maxlength: 100
                },
                Type: {
                    required: true
                },
                StartDate: { required: true }, EndDate: { required: true }, MinValue: { required: true, number: true, min: 0, max: 1000 }, Money: { required: true, number: true, min: 0.01, max: 1000 }, Status: { required: true }
            };
            basic_validate("EditPromotion", rules);
        });
    </script>
}

src/Sms.WebAdmin/Views/Promotion/Index.cshtml
@using Webdiyer.WebControls.Mvc
@using Sms.Common

@model  PagedList<Sms.Entity.Promotion>

<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">销售管理</a>
    <a href="javascript:void(0);" class="current">门店促销</a>
</div>

<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <a class="icon-list"></a>
            </span>
            <h5>门店促销</h5>
            <h5><a href="@Url.Action("Edit")" class="">添加</a></h5>
        </div>
        <div class="widget-content">
            @using (Html.BeginForm("Index", "Promotion", new { page = 1 }, FormMethod.Get))
            {
            <p>
                @Html.TextBox("keyword", "", new { @id = "keyword", type = "search", placeholder = "标题", style = "margin:0px 10px" })
                @Html.DropDownList("type", new SelectList(EnumHepler.GetEnumData(typeof(EnumHepler.PromotionType)), "Value", "Key"), null, new { @id = "type", style = "width:130px" })
                <input type="submit" class="btn" value="查询" onclick="if ($('#keyword').val() == '' && $('#type').val() == '') { return false; }" />
            </p>
            }
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered table-striped with-check">
                <thead>
                    <tr>
                        <th style="width: 22%">标题</th>
                        <th style="width: 18%">促销时间</th>
                        <th>类型</th>
                        <th style="width: 8%">最低金额</th>
                        <th style="width: 8%">满减 / 赠送</th>
                        <th>创建时间</th>
                        <th>创建人</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model.Count > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td class="center">
                                        @item.Title
                                    </td>
                                    <td class="center">
                                    @string.Format("{0:yyyy-MM-dd}", item.StartDate) 
                                    至
                                    @string.Format("{0:yyyy-MM-dd}", item.EndDate)</td>
                                    <td class="center">@EnumHepler.GetEnumDescription((EnumHepler.PromotionType)item.Type)</td>
                                    <td class="center">@item.MinValue</td>
                                    <td class="center">@item.Money</td>
                                    <td class="center">
                                    @string.Format("{0:yyyy-MM-dd HH:mm}", item.CreateTime)</td>
                                    <td class="center">@item.CreateUser</td>
                                    <td class="center">
                                        @EnumHepler.GetEnumDescription((EnumHepler.PromotionStatus)item.Status)
                                    </td>
                                    <td class="center">
                                        <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-mini tip-bottom" data-original-title="编辑"><i class="icon-pencil"></i></a>
                                        @if (item.Status == (int)EnumHepler.PromotionStatus.Available)
                                        {
                                            <a href="javascript:" class="btn btn-mini btn-danger tip-bottom" title="禁用" onclick="SetStatus(@item.Id,@((int)EnumHepler.PromotionStatus.Locked));"><i class="icon-lock icon-white"></i></a>
                                        }
                                        else if (item.Status == (int)EnumHepler.PromotionStatus.Locked)
                                        {
                                            <a href="javascript:" class="btn btn-mini btn-success tip-bottom" title="启用" onclick="SetStatus(@item.Id,@((int)EnumHepler.PromotionStatus.Available));"><i class="icon-check icon-white"></i></a>
                                        }
                                        <a href="javascript:" class="btn btn-mini btn-danger tip-bottom" title="删除" onclick="PromotionDelete(this,@item.Id);"><i class="icon-trash icon-white"></i></a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr style="">
                                <td colspan="9">
                                    <div class="list-none-data">  -- 暂无记录 -- </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        @if (Model.Count >= Sms.WebAdmin.Common.ConstFiled.PageSize)
        {
            <div class="center">
                <div class="dataTables_paginate paging_bootstrap pagination">
                    @Html.Pager(Model, new PagerOptions
               {
                   PageIndexParameterName = "page",
                   ContainerTagName = "ul",
                   DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
                   PagerItemTemplate = "<li>{0}</li>",
                   CurrentPagerItemTemplate = "<li class=\"active\"><a>{0}</a></li>",
                   PrevPageText = "上一页",
                   NextPageText = "下一页",
                   ShowFirstLast = false
               })
                </div>
            </div>
        }
    </div>
</div>
@section foot{
    <script type="text/javascript">
        $(function () {
            $("select").select2();
        });
        //更改状态
        function SetStatus(id, status) {
            if (confirm('确认要执行操作吗？')) {
                OnSubmiting();
                $.post("@Url.Action("UpdateStatus")", { "id": id, "status": status }, function (data) {
                    AjaxCompelement();
                    show_message(data.Status, data.MsgText, data.Url);
                }, "json");
            }
        }
        //删除
        function PromotionDelete(obj,id) {
            if (confirm('确认要删除该促销活动吗？')) {
                AjaxFunction("post", "@Url.Action("PromotionDelete")", { "id": id }, function (data) {
                    if (data.Status) { $(obj).parents("tr").remove(); }
                    show_message(data.Status, data.MsgText, data.Url);
                });
            }
        }
    </script>
}