src/Sms.WebAdmin/Controllers/ConsoleController.cs
using Sms.Common;
using Sms.Entity.ViewModel;
using Sms.WebAdmin.Common;
using Sms.WebAdmin.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Sms.WebAdmin.Controllers
{
    public class ConsoleController : BaseController
    {
        /// <summary>
        /// 控制台全局框架
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //根据登录用户的权限获取菜单节点，放到缓存中，下次直接从缓存读取
            List<MenuNode> menu = new List<MenuNode>();
            var cache = CacheHelper.GetCache(ConstFiled.GlobalMenu + CurrentLoginUser.Id);
            if (cache != null)
            {
                menu = cache as List<MenuNode>;
            }
            else
            {
                //1.从数据库查询
                //模块列表
                var moduleList = _repositoryFactory.ISystemModule.Where(m => m.IsDisplay && m.ParentId != 0, m => m.Sort, true).ToList();
                if (!CurrentLoginUser.IsSuperUser)
                {
                    if (!string.IsNullOrEmpty(CurrentLoginUser.RoleString))
                    {
                        IEnumerable<int> role = CurrentLoginUser.RoleString.Split(',').Select(m => Convert.ToInt32(m));
                        //找到拥有查看权限的模块id
                        var roleRight = _repositoryFactory.ISystemRoleRight.Where(m => role.Contains(m.RoleId) && m.RightId == (int)EnumHepler.ActionPermission.View).Select(m => m.ModuleId).Distinct();
                        //从所有模块中移除没有查看权限的
                        moduleList.RemoveAll(m => !roleRight.Contains(m.Id));
                    }
                    else
                    {
                        //一个角色都么有肯定也就没有任何菜单了
                        moduleList.Clear();
                    }
                }
                var top = _repositoryFactory.ISystemModule.Where(m => m.IsDisplay && m.ParentId == 0, m => m.Sort, true).Select(m => new { m.Id, m.Name, m.Url }).ToList();
                foreach (var module in top)
                {
                    var child = moduleList.Where(m => m.ParentId == module.Id).OrderBy(m => m.Sort);
                    if (child.Count() > 0)
                    {
                        MenuNode node = new MenuNode();
                        node.Title = module.Name;
                        node.Id = module.Id;
                        foreach (var c in child)
                        {
                            node.ChildNode.Add(new MenuNode() { Id = c.Id, Title = c.Name, Url = c.Url });
                        }
                        menu.Add(node);
                    }
                }
                //2.放入缓存
                CacheHelper.SetCache(ConstFiled.GlobalMenu + CurrentLoginUser.Id, menu, TimeSpan.FromMinutes(10));
            }
            ViewBag.CurrentUser = CurrentLoginUser;
            return View(menu);
        }

        /// <summary>
        /// 控制台首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Home()
        {
            return View();
        }

        /// <summary>
        /// 获取当前登录用户的信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetLoginUserDetail()
        {
            var current = CurrentLoginUser;
            if (current.IsSuperUser)
            {
                string path = HttpContext.Server.MapPath("/App_Data/adminconfig.xml");
                XmlDocument config = new XmlDocument();
                config.Load(path);
                return Json(new TipMessage()
                {
                    Status = true,
                    MsgText = "获取信息成功",
                    Data = new
                    {
                        UserName = config.SelectSingleNode("root/SuperUser").InnerText,
                        TrueName = "超级管理员",
                        LinkPhone = "",
                        LastLoginTime = config.SelectSingleNode("root/LastLoginTime").InnerText,
                        CreateTime = "系统自动创建",
                        RoleList = "所有"
                    }
                }, JsonRequestBehavior.DenyGet);
            }
            var user = _repositoryFactory.ISystemUser.Single(m => m.Id == current.Id);
            if (user != null)
            {
                StringBuilder roleString = new StringBuilder();
                int[] roleArry = user.RoleList.Split(',').Select(m => int.Parse(m)).ToArray();
                var roles = _repositoryFactory.ISystemRole.Where(m => roleArry.Contains(m.Id)).Select(m => m.Name).ToList();
                foreach (var item in roles)
                {
                    roleString.Append(item + "、");
                }
                return Json(new TipMessage()
                {
                    Status = true,
                    MsgText = "获取信息成功",
                    Data = new
                    {
                        user.UserName,
                        user.TrueName,
                        user.LinkPhone,
                        LastLoginTime = user.LastLoginTime != null ? user.LastLoginTime.Value.ToString("yyyy-MM-dd HH:mm:ss") : "",
                        CreateTime = user.CreateTime != null ? user.CreateTime.Value.ToString("yyyy-MM-dd HH:mm:ss") : "",
                        RoleList = roleString.Length > 0 ? roleString.ToString().TrimEnd('、') : ""
                    }
                }, JsonRequestBehavior.DenyGet);
            }
            return Json(new TipMessage() { Status = false, MsgText = "获取信息失败" }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 清除缓存和session
        /// </summary>
        /// <returns></returns>
        public ActionResult ClearCache()
        {
            var cache = HttpContext.Cache.GetEnumerator();
            while (cache.MoveNext())
            {
                HttpContext.Cache.Remove(cache.Key.ToString());
            }
            Session.Clear();
            return Json(new TipMessage() { Status = true, MsgText = "清除成功！" }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 当前用户修改密码
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> ChangePassword(ChangePassword model)
        {
            if (ModelState.IsValid)
            {
                if (!model.ConfirmNewPwd.Equals(model.NewPwd))
                {
                    return ShowResultMessage(new TipMessage() { Status = false, MsgText = "确认新密码错误！" });
                }
                var current = CurrentLoginUser;
                if (current.IsSuperUser)
                {
                    string path = HttpContext.Server.MapPath("/App_Data/adminconfig.xml");
                    XmlDocument config = new XmlDocument();
                    config.Load(path);
                    var old = config.SelectSingleNode("root/SuperUserPassword").InnerText;
                    if (old.Equals(SecurityHelper.MD5(model.OldPwd)))
                    {

                        config.SelectSingleNode("root/SuperUserPassword").InnerText = SecurityHelper.MD5(model.NewPwd);
                        config.Save(path);
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "修改成功！", Url = Url.Action("LoginOut", "Login") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "旧密码输入错误！" });
                    }
                }
                else
                {
                    var user = await _repositoryFactory.ISystemUser.SingleAsync(m => m.Id == CurrentLoginUser.Id);
                    if (!user.Password.Equals(SecurityHelper.MD5(model.OldPwd)))
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "旧密码输入错误！" });
                    }
                    user.Password = SecurityHelper.MD5(model.NewPwd);
                    _repositoryFactory.ISystemUser.Modify(user, "Password");
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "修改成功！", Url = Url.Action("LoginOut", "Login") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "修改失败！" });
                    }
                }
            }
            return View();
        }
    }
}

src/Sms.WebAdmin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sms.Common;
using Sms.WebAdmin.Filter;
using Sms.WebAdmin.Common;
using Webdiyer.WebControls.Mvc;
using Sms.Entity;
using Sms.Entity.ViewModel;
using System.Threading.Tasks;

namespace Sms.WebAdmin.Controllers
{
    public class RolesController : BaseController
    {
        #region 角色的基础信息维护

        /// <summary>
        /// 角色列表页，分页，搜索
        /// </summary>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Index(string keyword = "")
        {
            var list = _repositoryFactory.ISystemRole.Where(c => c.Status != (int)EnumHepler.RoleStatus.Deleted);
            //搜索关键字过滤
            if (!string.IsNullOrEmpty(keyword))
            {
                list = list.Where(c => c.Name.Contains(keyword) || c.Remark.Contains(keyword));
            }
            list = list.OrderByDescending(m => m.Sort);
            var pagerList = list.ToPagedList(PageIndex, ConstFiled.PageSize);
            return View(pagerList);
        }

        /// <summary>
        /// 角色信息编辑页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Edit(int? id)
        {
            var model = _repositoryFactory.ISystemRole.Single(m => m.Id == id);
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// 角色信息编辑处理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(true, EnumHepler.ActionPermission.New)]
        public async Task<ActionResult> Edit(SystemRole model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id != 0)
                {
                    _repositoryFactory.ISystemRole.Modify(model, "Name", "Sort", "Remark");
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "编辑成功！", Url = Url.Action("Index") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "编辑失败！", Url = Url.Action("Edit", new { id = model.Id }) });
                    }
                }
                else
                {
                    model.Status = (int)EnumHepler.RoleStatus.Available;
                    model.CreateTime = DateTime.Now;
                    model.CreateUser = CurrentLoginUser.UserName;
                    _repositoryFactory.ISystemRole.Add(model);
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "添加成功！", Url = Url.Action("Index") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "添加失败！", Url = Url.Action("Index") });
                    }
                }
            }
            return ShowResultMessage(new TipMessage() { Status = false, MsgText = "未知操作结果！", Url = Url.Action("Index") });
        }

        /// <summary>
        /// 修改角色状态
        /// </summary>
        /// <param name="id">角色id</param>
        /// <param name="status">更新的状态编号</param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.ChangeStatus)]
        public async Task<ActionResult> UpdateStatus(int id, int status)
        {
            var entity = _repositoryFactory.ISystemRole.Single(m => m.Id == id);
            if (entity != null)
            {
                entity.Status = status;
                _repositoryFactory.ISystemRole.Modify(entity, "Status");
                if (await _repositoryFactory.SaveChanges() > 0)
                {
                    return Json(new TipMessage() { Status  = true, MsgText = "操作成功" }, JsonRequestBehavior.DenyGet);
                }
            }
            return Json(new TipMessage() { Status  = false, MsgText = "操作失败" }, JsonRequestBehavior.DenyGet);
        }
        #endregion


        #region 角色权限操作

        /// <summary>
        /// 权限编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.ViewRight)]
        public ActionResult RightConfig(int id)
        {
            ViewBag.RoleId = id;
            //模块列表
            var moduleList = _repositoryFactory.ISystemModule.WhereJoin(m => m.IsDisplay, m => m.Sort, true, "SystemModuleRight").ToList();
            //该角色已保存的权限
            var existRight = _repositoryFactory.ISystemRoleRight.Where(m => m.RoleId == id).ToList();
            //页面展示的数据
            var viewList = new List<RoleModuleRight>();
            foreach (var module in moduleList)
            {
                var viewModel = new RoleModuleRight();
                viewModel.Name = module.Name;
                viewModel.Parent = module.ParentId;
                viewModel.Value = module.Id;
                viewModel.Sort = module.Sort;
                foreach (var mr in module.SystemModuleRight)
                {
                    viewModel.RightList.Add(new ModuleRight()
                    {
                        Value = mr.RightId,
                        Text = EnumHepler.GetEnumDescription(typeof(EnumHepler.ActionPermission), mr.RightId),
                        Checked = existRight.Count(m => m.RightId == mr.RightId && m.ModuleId == module.Id) > 0
                    });
                }
                viewList.Add(viewModel);
            }
            return View(viewList);
        }

        /// <summary>
        /// 保存页面选择的权限
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.ChangeRight)]
        public async Task<ActionResult> SaveModuleRight(string rightStr, int role)
        {
            try
            {
                if (string.IsNullOrEmpty(rightStr))
                {
                    //为空的时候是清空所有权限
                    _repositoryFactory.ISystemRoleRight.DeleteBy(m => m.RoleId == role);
                }
                else
                {
                    //不为空的时候要新增和删除
                    List<string> rightArry = rightStr.TrimEnd(',').Split(',').ToList();
                    var existRight = _repositoryFactory.ISystemRoleRight.Where(m => m.RoleId == role).ToList();
                    //从新权限中移除已存在的，删除数据库中多余的
                    string viewStr = string.Empty;
                    foreach (var exist in existRight)
                    {
                        viewStr = exist.RightId + "|" + exist.ModuleId;
                        if (rightArry.Contains(viewStr))
                        {
                            rightArry.Remove(viewStr);
                        }
                        else
                        {
                            _repositoryFactory.ISystemRoleRight.Delete(exist);
                        }
                    }
                    //剩下的新权限就要新增了
                    if (rightArry.Count() > 0)
                    {
                        foreach (string r in rightArry)
                        {
                            var values = r.Split('|').Select(m => Convert.ToInt32(m)).ToArray();
                            _repositoryFactory.ISystemRoleRight.Add(new SystemRoleRight() { ModuleId = values[1], RightId = values[0], RoleId = role });
                        }
                    }
                }
                await _repositoryFactory.SaveChanges();
                return Json(new TipMessage(){ Status = true, MsgText = "保存成功！", Url = Url.Action("RightConfig", new { id = role }) });
            }
            catch (Exception ex)
            {
                return Json(new TipMessage() { Status = false, MsgText = "保存失败！" });
            }
        }
        #endregion
    }
}

src/Sms.WebAdmin/Views/Roles/Edit.cshtml
@model Sms.Entity.SystemRole


<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">用户管理</a>
    <a href="javascript:void(0);" title="角色列表" class="tip-bottom">角色管理</a>
    <a href="javascript:void(0);" class="current">编辑角色信息</a>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                @using (Ajax.BeginForm("Edit", "Roles", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "OnSubmiting", OnComplete = "AjaxCompelement" }, new { @class = "form-horizontal", id = "RolesEdit" }))
                {
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-pencil"></i>
                        </span>
                        <h5>编辑角色信息</h5>
                    </div>
                    <div class="widget-content nopadding">

                        <div class="control-group">
                            <label class="control-label">名称</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Name)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">排序</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.Sort)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">备注</label>
                            <div class="controls">
                                @Html.TextAreaFor(model => model.Remark)
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="submit" value="保存" class="btn btn-primary" />
                            <input type="button" value="返回" class="btn" onclick="location.href='@Url.Action("Index")    '" />
                        </div>
                    </div>
                    
                }
            </div>
        </div>
    </div>
</div>
@section foot{
    <script>
        $(function() {
            var rules={ Name:{  required:true  },Sort:{ required:true,digits:true }};
            basic_validate("RolesEdit",rules);
        });
    </script>
}

src/Sms.WebAdmin/Views/Roles/Index.cshtml
@using Webdiyer.WebControls.Mvc
@using Sms.Common

@model PagedList<Sms.Entity.SystemRole>


<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">用户管理</a>
    <a href="javascript:void(0);" class="current">角色管理</a>
</div>

<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <a class="icon-list"></a>
            </span>
            <h5>角色列表</h5>
            <h5><a href="@Url.Action("Edit")" class="">添加</a></h5>
        </div>
        <div class="widget-content">
            @using (Html.BeginForm("Index", "Role", new { page = 1 }, FormMethod.Get))
            { 
                <p>
                    @Html.TextBox("keyword", "", new { @id = "keyword", type = "search", placeholder = "名称、备注", style = "margin:0px 10px" })
                    <input type="submit" class="btn" value="查询" onclick="if ($('#keyword').val() == '') { return false; }" />
                </p>
            }
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered table-striped with-check">
                <thead>
                    <tr>
                        <th style="width: 35%">角色名称</th>
                        <th>备注</th>
                        <th>排序</th>
                        <th>创建时间</th>
                        <th>创建人</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="center" style="width: 35%">@item.Name</td>
                            <td class="center">@item.Remark</td>
                            <td class="center">@item.Sort</td>
                            <td class="center">@string.Format("{0:yyyy-MM-dd HH:mm:ss}", item.CreateTime)</td>
                            <td class="center">@item.CreateUser</td>
                            <td class="center">@Html.Raw(item.Status == (int)EnumHepler.RoleStatus.Available ? "<i class=\"icon-ok tip-bottom\" title=\"有效\"></i>" : (item.Status == (int)EnumHepler.RoleStatus.Lock ? "<i class=\"icon-remove tip-bottom\" title=\"已锁定\"></i>" : ""))</td>
                            <td class="center">
                                <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-mini tip-bottom" data-original-title="编辑"><i class="icon-pencil"></i></a>
                                @if (item.Status == (int)EnumHepler.UserStatus.Available)
                                {
                                    <a href="javascript:" class="btn btn-mini btn-danger tip-bottom" title="禁用" onclick="SetStatus(@item.Id,@((int)EnumHepler.RoleStatus.Lock));"><i class=" icon-lock icon-white"></i></a>
                                }
                                else if (item.Status == (int)EnumHepler.UserStatus.Lock)
                                {
                                    <a href="javascript:" class="btn btn-mini btn-success tip-bottom" title="启用" onclick="SetStatus(@item.Id,@((int)EnumHepler.RoleStatus.Available));"><i class="icon-check icon-white"></i></a>
                                }

                                <a href="@Url.Action("RightConfig", new { id = item.Id })" class="btn btn-mini btn-info tip-bottom" data-original-title="权限配置"><i class="icon-cog  icon-white"></i></a>

                                <a href="javascript:" class="btn btn-mini btn-danger tip-bottom" title="删除" onclick="DeleteRole(@item.Id,@((int)EnumHepler.RoleStatus.Deleted),this);"><i class="icon-trash icon-white"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="center">
            <div class="dataTables_paginate paging_bootstrap pagination">
                @Html.Pager(Model, new PagerOptions
                       {
                           PageIndexParameterName = "page",
                           ContainerTagName = "ul",
                           DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
                           PagerItemTemplate = "<li>{0}</li>",
                           CurrentPagerItemTemplate = "<li class=\"active\"><a>{0}</a></li>",
                           PrevPageText = "上一页",
                           NextPageText = "下一页",
                           ShowFirstLast = false
                       })
            </div>
        </div>
    </div>
</div>
@section foot{
    <script type="text/javascript">
        //更改状态
        function SetStatus(id, status) {
            if (confirm('确认要执行操作吗？')) {
                OnSubmiting();
                $.post("@Url.Action("UpdateStatus")", { "id": id, "status": status }, function (data) {
                    AjaxCompelement();
                    show_message(data.Status, data.MsgText, data.Url);
                }, "json");
            }
        }
        function DeleteRole(id, status, obj) {
            if (confirm('确认要删除该角色吗？请谨慎操作~')) {
                OnSubmiting();
                $.post("@Url.Action("UpdateStatus")", { "id": id, "status": status }, function (data) {
                    AjaxCompelement();
                    if (data.Status) {
                        $(obj).parents("tr").remove();
                    }
                    else {
                        show_message(false, data.MsgText, data.Url);
                    }
                }, "json");
            }
        }
    </script>
}

src/Sms.WebAdmin/Views/Roles/RightConfig.cshtml
@model List<Sms.Entity.ViewModel.RoleModuleRight>


@section head{
    <link href="~/Content/tree.css" rel="stylesheet" />
    <style type="text/css">
        .well label {
            display: initial;
            margin-left: 10px;
            color: #08c;
        }
    </style>
}

<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">用户管理</a>
    <a href="javascript:void(0);" class="tip-bottom" title="角色列表">角色管理</a>
    <a href="javascript:void(0);" class="current">角色权限配置</a>
</div>


<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <h2 style="line-height: 29px; margin: 3px 0px; padding-left: 30px">
                <button class="btn btn-primary" onclick="" id="btnSave"><i class="icon-ok icon-white"></i>保存</button>
                <button class="btn btn-success" id="btnCheckAll">全选</button>
                <button class="btn btn-info" id="btnToggle">全部收起</button>
                <button class="btn" onclick="history.back();">返回</button>
            </h2>
        </div>

        <div class="widget-content nopadding">
            <div class="tree well">
                <ul>

                    @{
                        var topList = Model.Where(m => m.Parent == 0).OrderBy(m => m.Sort);
                        foreach (var top in topList)
                        {
                        <li>
                            @{
                            var childList = Model.Where(m => m.Parent == top.Value).OrderBy(m => m.Sort);
                        
                                <span><i class="@(childList.Count() > 0 ? "icon-minus-sign" : "icon-flag")"></i>@(top.Name) </span>
                           
                                <ul>
                                    @foreach (var child in childList)
                                    {
                                        <li>
                                            <span><i class="icon-flag"></i>@child.Name </span>
                                            @foreach (var right in child.RightList)
                                            {
                                                <label>
                                                    <input type="checkbox" class="checkbox" value="@(right.Value + "|" + child.Value)" @(right.Checked ? " checked=\"checked\"" : "")  />@right.Text</label>
                                            }
                                        </li>
                                    }
                                </ul>
                            
                            }
                        </li>
                        }
                    }


                </ul>
            </div>
        </div>

    </div>
</div>
@section foot{
    <script type="text/javascript">
        $(function () {
            $("#btnSave").click(function () {
                OnSubmiting();
                var selectedItem = $("input:checkbox:checked");
                var idStr = '';
                $.each(selectedItem, function (index, obj) {
                    idStr += obj.value + ',';
                });
                $.post("@Url.Action("SaveModuleRight")", { "rightStr":idStr,"role": @ViewBag.RoleId }, function (data) {
                    AjaxCompelement();
                    show_message(data.Status, data.MsgText, data.Url);
                }, "json");
            });
        
        })

    </script>}