src/Sms.WebAdmin/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sms.WebAdmin.Filter;
using Sms.Common;
using Sms.Entity;
using System.Threading.Tasks;
using Sms.Entity.ViewModel;
using Webdiyer.WebControls.Mvc;
using Sms.WebAdmin.Common;
using System.Xml;

namespace Sms.WebAdmin.Controllers
{
    public class SystemController : BaseController
    {

        #region 系统模块管理部分

        /// <summary>
        /// 模块树形列表页
        /// </summary>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Module()
        {
            return View(_repositoryFactory.ISystemModule.Where(m => m.Id > 0).ToList());
        }

        /// <summary>
        /// 模块编辑页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult ModuleEdit(int? id)
        {
            var ddlParent = new SelectList(_repositoryFactory.ISystemModule.Where(m => m.IsDisplay && m.ParentId == 0, m => m.Sort, true), "Id", "Name").ToList();
            ddlParent.Insert(0, new SelectListItem() { Text = "无", Value = "0" });
            ViewBag.ddlParent = ddlParent;
            var model = _repositoryFactory.ISystemModule.Single(m => m.Id == id);
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// 模块编辑逻辑处理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(true, EnumHepler.ActionPermission.New)]
        public async Task<ActionResult> ModuleEdit(SystemModule model)
        {
            if (ModelState.IsValid)
            {
                List<int> rightList = new List<int>();
                if (!string.IsNullOrEmpty(Request.Params["rightlist"]))
                {
                    rightList = Request.Params["rightlist"].Split(',').Select(m => int.Parse(m)).ToList();
                }
                if (model.Id != 0)
                {
                    _repositoryFactory.ISystemModule.Modify(model, "Name", "ParentId", "Sort", "Url", "IsDisplay");
                    //修改权限
                    var existRight = _repositoryFactory.ISystemModuleRight.Where(m => m.ModuleId == model.Id).ToList();
                    //从新权限中移除已存在的，删除数据库中多余的
                    foreach (var exist in existRight)
                    {
                        if (rightList.Contains(exist.RightId))
                        {
                            rightList.Remove(exist.RightId);
                        }
                        else
                        {
                            _repositoryFactory.ISystemModuleRight.Delete(exist);
                        }
                    }
                    //剩下的新权限就要新增了
                    if (rightList.Count() > 0)
                    {
                        foreach (int r in rightList)
                        {
                            _repositoryFactory.ISystemModuleRight.Add(new SystemModuleRight() { ModuleId = model.Id, RightId = r });
                        }
                    }
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "编辑成功！", Url = Url.Action("Module") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "编辑失败！" });
                    }
                }
                else
                {
                    model.CreateTime = DateTime.Now;
                    model.CreateUser = CurrentLoginUser.UserName;
                    _repositoryFactory.ISystemModule.Add(model);
                    //增加权限
                    if (rightList.Count() > 0)
                    {
                        foreach (int r in rightList)
                        {
                            _repositoryFactory.ISystemModuleRight.Add(new SystemModuleRight() { ModuleId = model.Id, RightId = r });
                        }
                    }
                    if (await _repositoryFactory.SaveChanges() > 0)
                    {
                        return ShowResultMessage(new TipMessage() { Status = true, MsgText = "添加成功！", Url = Url.Action("Module") });
                    }
                    else
                    {
                        return ShowResultMessage(new TipMessage() { Status = false, MsgText = "添加失败！" });
                    }
                }
            }
            return ShowResultMessage(new TipMessage() { Status = false, MsgText = "未知操作结果！", Url = Url.Action("Module") });
        }

        /// <summary>
        /// 异步加载模块拥有的权限
        /// </summary>
        /// <returns>json数据</returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public JsonResult LoadModuleRight(int module)
        {
            var list = new List<SelectItem>();
            //模块拥有的权限
            List<int> existRight = new List<int>();
            if (module != 0)
            {
                existRight = _repositoryFactory.ISystemModuleRight.Where(m => m.ModuleId == module).Select(m => m.RightId).ToList();
            }
            //所有权限
            var allRight = EnumHepler.GetEnumData(typeof(EnumHepler.ActionPermission));
            foreach (var right in allRight)
            {
                list.Add(new SelectItem() { Text = right.Key, Value = right.Value, Selected = existRight.Contains(right.Value) });
            }
            return Json(new TipMessage() { Status = true, Data = list }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 异步删除模块
        /// </summary>
        /// <param name="module"></param>
        /// <returns></returns>
        [HttpPost]
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.Delete)]
        public async Task<ActionResult> ModuleDelete(int module)
        {
            //1.先检查是否有子模块
            var childCount = _repositoryFactory.ISystemModule.Count(m => m.ParentId == module);
            if (childCount > 0)
            {
                return Json(new TipMessage() { Status = false, MsgText = "该模块下有子模块，无法删除！" });
            }
            //2.删除关联的信息
            _repositoryFactory.ISystemModuleRight.DeleteBy(m => m.ModuleId == module);
            _repositoryFactory.ISystemRoleRight.DeleteBy(m => m.ModuleId == module);
            //3.删除模块记录
            _repositoryFactory.ISystemModule.DeleteBy(m => m.Id == module);
            if (await _repositoryFactory.SaveChanges() > 0)
            {
                return Json(new TipMessage() { Status = true, MsgText = "删除成功" });
            }
            else
            {
                return Json(new TipMessage() { Status = false, MsgText = "删除失败" });
            }
        }
        #endregion


        /// <summary>
        /// 系统日志页，分页，搜索
        /// </summary>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult Log(int? type, string keyword = "")
        {
            var list = _repositoryFactory.ISysLog.Where(c => c.Id > 0);
            //搜索关键字过滤
            if (type != null && type != -1)
            {
                list = list.Where(c => c.Type == type);
            }
            if (!string.IsNullOrEmpty(keyword))
            {
                list = list.Where(c => c.Remark.Contains(keyword));
            }
            list = list.OrderByDescending(c => c.CreateTime);
            var pagerList = list.ToPagedList(PageIndex, ConstFiled.PageSize);
            return View(pagerList);
        }

        /// <summary>
        /// 请求源设置
        /// </summary>
        /// <returns></returns>
        [PermissionFilterAttribute(false, EnumHepler.ActionPermission.View)]
        public ActionResult RequestControl()
        {
            IpConfig config = new IpConfig() { };
            lock (this)
            {
                XmlDocument xml = new XmlDocument();
                xml.Load(HttpContext.Server.MapPath("/App_Data/iptable.xml"));
                config.Status = xml.SelectSingleNode("root/IpControl").InnerText.ToLower();
                config.AddressList = new List<string>();
                XmlNodeList router = xml.SelectSingleNode("root/Router").ChildNodes;
                foreach (var item in router)
                {
                    config.AddressList.Add(((XmlNode)item).InnerText);
                }
            }
            return View(config);
        }

        [HttpPost, PermissionFilterAttribute(false, EnumHepler.ActionPermission.Edit)]
        public ActionResult RequestControl(FormCollection form)
        {
            IpConfig config = new IpConfig() { };
            lock (this)
            {
                try
                {
                    string status = form["ipstatus"];
                    string[] router = form["address"].ToString().Split(',');
                    XmlDocument xml = new XmlDocument();
                    string path = HttpContext.Server.MapPath("/App_Data/iptable.xml");
                    xml.Load(path);
                    xml.SelectSingleNode("root/IpControl").InnerText = status ;

                    var routerNode = xml.SelectSingleNode("root/Router");
                    routerNode.RemoveAll();
                    foreach (var item in router)
                    {
                        XmlElement xe = xml.CreateElement("Address");
                        xe.InnerText = item;
                        routerNode.AppendChild(xe);
                    }
                    xml.Save(path);

src/Sms.WebAdmin/Views/System/Log.cshtml
@using Webdiyer.WebControls.Mvc
@using Sms.Common

@model  PagedList<Sms.Entity.SysLog>

<div id="breadcrumb">
    <a href="@Url.Action("Home","Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">系统管理</a>
    <a href="javascript:void(0);" class="current">系统日志</a>
</div>

<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <a class="icon-list"></a>
            </span>
            <h5>系统日志</h5>
        </div>
        <div class="widget-content">
            @using (Html.BeginForm("Log", "System", new { page = 1 }, FormMethod.Get))
            {
                <p>
                    @Html.TextBox("keyword", "", new { @id = "keyword", type = "search", placeholder = "关键字", style = "margin:0px 10px" })
                    @Html.DropDownList("type", new SelectList(EnumHepler.GetEnumData(typeof(EnumHepler.LogType)), "Value", "Key"), null, new { @id = "type", style = "width:100px" })
                    <input type="submit" class="btn" value="查询" onclick="if ($('#keyword').val() == '' && $('#type').val() == '') { return false; }" />
                </p>
            }
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered table-striped with-check">
                <thead>
                    <tr>
                        <th style="width:15%">时间</th>
                        <th style="width:10%">类型</th>
                        <th>内容</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="center" style="width:15%">@string.Format("{0:yyyy-MM-dd HH:mm:ss}", item.CreateTime)</td>
                            <td class="center">@(EnumHepler.GetEnumDescription((EnumHepler.LogType)item.Type))</td>
                            <td>@item.Remark</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="center">
            <div class="dataTables_paginate paging_bootstrap pagination">
                @Html.Pager(Model, new PagerOptions
           {
               PageIndexParameterName = "page",
               ContainerTagName = "ul",
               DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
               PagerItemTemplate = "<li>{0}</li>",
               CurrentPagerItemTemplate = "<li class=\"active\"><a>{0}</a></li>",
               PrevPageText = "上一页",
               NextPageText = "下一页",
               ShowFirstLast = false
           })
            </div>
        </div>
    </div>
</div>

@section foot{
    <script type="text/javascript">
        $(function () {
            $("select").select2();
        });
    </script>
}

src/Sms.WebAdmin/Views/System/Module.cshtml
@model IEnumerable<Sms.Entity.SystemModule>

@section head{
    <link href="~/Content/tree.css" rel="stylesheet" />
}

<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">系统管理</a>
    <a href="javascript:void(0);" class="current">模块管理</a>
</div>

<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <h2 style="line-height: 29px; margin: 3px 0px; padding-left: 30px">
                <a class="btn btn-primary" href="@Url.Action("ModuleEdit", "System")" ><i class="icon-plus icon-white"></i>创建新模块</a>
                <button class="btn btn-info" id="btnToggle">全部收起</button>
            </h2>
        </div>

        <div class="widget-content nopadding">
            <div class="tree well">
                <ul>

                    @{
                        var topList = Model.Where(m => m.ParentId == 0).OrderBy(m => m.Sort);
                        foreach (var top in topList)
                        {
                        <li>
                            @{
                            var childList = Model.Where(m => m.ParentId == top.Id).OrderBy(m => m.Sort);
                        
                                <span><i class="@(childList.Count() > 0 ? "icon-minus-sign" : "icon-flag")"></i>@top.Name
                                </span>
                                
                            if (!top.IsDisplay)
                            {
                                <span class="badge">已隐藏</span>
                            }
                                    
                                <a href="@Url.Action("ModuleEdit", new { id = top.Id })"  title="编辑" ><i class="icon-edit"></i></a>
                                <a href="javascript:" class="delete" title="删除" module="@top.Id"><i class="icon-trash"></i></a>
                                <ul>
                                    @foreach (var child in childList)
                                    {
                                        <li>
                                            <span><i class="icon-flag"></i><a href="javascript:">@child.Name</a>
                                                @{if (!child.IsDisplay)
                                                  {
                                                    <span class="badge">已隐藏</span>
                                                  }
                                                }
                                                <a href="@Url.Action("ModuleEdit", new { id = child.Id })" class="tip-bottom" title="编辑" ><i class="icon-edit"></i></a>
                                                <a href="javascript:" class="tip-bottom delete" title="删除" module="@child.Id"><i class="icon-trash"></i></a>
                                            </span>
                                        </li>
                                    }
                                </ul>
                            
                            }
                        </li>
                        }
                    }


                </ul>
            </div>
        </div>

    </div>
</div>


@section foot{
    <script type="text/javascript">
        $(function () {
            $(".delete").bind("click", function () {
                if (confirm('删除该模块会级联删除与其有关的数据，确认要删除吗？ \n\n请谨慎操作！')) {
                    OnSubmiting();
                    var obj = $(this);
                    $.post("@Url.Action("ModuleDelete")", { "module": obj.attr("module") }, function (data) {
                        AjaxCompelement();
                        if (data.Status) {
                            obj.parent().parent().remove();
                        }
                        else {
                            show_message(false, data.MsgText, data.Url);
                        }
                    }, "json");
                }
            });
        });
    </script>
}

src/Sms.WebAdmin/Views/System/ModuleEdit.cshtml
@model Sms.Entity.SystemModule

<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">系统管理</a>
    <a href="@Url.Action("Index", new { exhibitionId = ViewBag.Exhibition })" class="tip-bottom" title="模块列表">模块管理</a>
    <a href="javascript:void(0);" class="current">编辑模块信息</a>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                @using (Ajax.BeginForm("ModuleEdit", "System", null, new AjaxOptions() { HttpMethod = "Post", OnBegin = "OnSubmiting", OnComplete = "AjaxCompelement" }, new { @class = "form-horizontal", id = "ModuleEdit" }))
                {
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-pencil"></i>
                        </span>
                        <h5>编辑模块信息</h5>
                    </div>
                    <div class="widget-content nopadding">

                        <div class="control-group">
                            <label class="control-label">模块名称</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Name)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">所属模块</label>
                            <div class="controls">
                                @Html.DropDownListFor(model => model.ParentId, ViewBag.ddlParent as List<SelectListItem>, "-请选择-")
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">排序</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.Sort)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">是否显示</label>
                            <div class="controls">
                                <label>@Html.CheckBoxFor(model => model.IsDisplay, new { @checked = "checked" }) </label>
                            </div>
                        </div>
                        <div class="control-group" id="txtUrl" style="display:@(Model != null && Model.ParentId != 0 ? "block" : "none")">
                            <label class="control-label">链接地址</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Url)
                            </div>
                        </div>
                        <div class="control-group" id="ddlRight" style="display:@(Model != null && Model.ParentId != 0 ? "block" : "none")">
                            <label class="control-label">操作权限</label>
                            <div class="controls">
                                <select multiple="multiple" id="RightList" style="width: 350px" name="rightlist">
                                </select>
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="submit" value="保存" class="btn btn-primary" />
                            <input type="button" value="返回" class="btn" onclick="location.href='@Url.Action("Module", "System")    '" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section foot{
    <script>
        $(function() {
            var rules={ Name:{ required:true },Sort:{ required:true,digits:true },ParentId:{required:true},Url:{required:true}};
            basic_validate("ModuleEdit",rules);
            $("#ParentId").change(function(){
                if(this.value!=""&&this.value!="0"){
                    $("#txtUrl,#ddlRight").show('fast');
                }
                else
                {
                    $("#txtUrl,#ddlRight").hide('fast');
                }
            });
            $.post("@Url.Action("LoadModuleRight")",{"module":@(Model != null ? Model.Id : 0)},function(data){
                if(data.Status){
                    $.each(data.Data,function(index,item){
                        $("#RightList").append("<option value=\""+item.Value+"\" "+(item.Selected?"selected=\"selected\"":"")+" >"+item.Text+"</option>");
                    });
                    $("#RightList").select2();
                }
                else
                {
                    show_message(false, data.MsgText, data.Url);
                }
            },"json");
        });
    </script>
}

src/Sms.WebAdmin/Views/System/RequestControl.cshtml
@model Sms.Entity.ViewModel.IpConfig

<div id="breadcrumb">
    <a href="@Url.Action("Home", "Console")" title="首页" class="tip-bottom"><i class="icon-home"></i>首页</a>
    <a href="javascript:void(0);" class="tip-bottom">系统管理</a>
    <a href="javascript:void(0);" class="current">IP白名单</a>
</div>

<div class="container-fluid">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <a class="icon-list"></a>
            </span>
            <h5>IP白名单</h5>
        </div>
        <div class="widget-content nopadding">
            <form class="form-horizontal" id="mainform" method="post">
                <div class="control-group">
                    <label class="control-label">IP限制</label>
                    <div class="controls">
                        <label>@Html.CheckBox("ipstatus", Model != null && Model.Status == "true" ? true : false, new { id = "ckb_ip_control" }) 开启</label>
                    </div>
                </div>
                <div id="main_router">
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            <input type="button" value="新增IP地址" class="btn btn-info" onclick="AddControl();" />
                        </div>
                    </div>
                    <div id="router_list">
                        @{ if (Model != null && Model.AddressList.Count > 0)
                            {
                                foreach (var item in Model.AddressList)
                                {
                                    <div class="control-group">
                                        <label class="control-label">IP地址</label>
                                        <div class="controls">
                                            <input type="text" value="@item" name="address" maxlength="15" />
                                            &nbsp;
                                            <input type="button" value="移除" class="btn btn-danger" onclick="$(this).parent().parent().remove();" />
                                        </div>
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
                <div class="form-actions" style="padding-left: 13%">
                    <input type="button" value="保存" class="btn btn-primary" id="btnSave" />
                </div>
            </form>
        </div>

        <div style="display: none" id="demo_control">
            <div class="control-group">
                <label class="control-label">IP地址</label>
                <div class="controls">
                    <input type="text" value="" name="address" maxlength="15" />
                    &nbsp;
                    <input type="button" value="移除" class="btn btn-danger" onclick="$(this).parent().parent().remove();" />
                </div>
            </div>
        </div>
    </div>
</div>

@section foot{
    <script src="~/Scripts/jquery.form.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#btnSave").bind("click", function () {
                $("#uniform-ckb_ip_control").next().remove();
                var validate = true;
                $.each($("#router_list .control-group"), function (index, item) {
                    var address = $(item).find("input[name='address']");
                    if (address.val() == "") {
                        address.focus();
                        validate &= false;
                        return;
                    }
                });
                if (validate) {
                    $("#mainform").ajaxSubmit({
                        beforeSubmit: function () {
                            OnSubmiting();
                        },
                        success: function (obj) {
                            AjaxCompelement();
                            show_message(obj.Status, obj.MsgText, obj.Url);
                        }
                    });
                }
            });
        });
        function AddControl() {
            $("#router_list").append($("#demo_control").html());
        }
    </script>
}